In [149]:
# Verifying data path

import os
import glob
import pandas as pd

paths = glob.glob("data/raw/**/*", recursive=True)

files = []
for item in paths:
    if os.path.isfile(item):
        files.append(item)

length = len(files)

print(files)
print(f"\n total files: {length}")

['data/raw\\delay\\TTC Subway Delay Data since 2025.csv', 'data/raw\\delay\\ttc-subway-delay-data-2018.xlsx', 'data/raw\\delay\\ttc-subway-delay-data-2019.xlsx', 'data/raw\\delay\\ttc-subway-delay-data-2020.xlsx', 'data/raw\\delay\\ttc-subway-delay-data-2021.xlsx', 'data/raw\\delay\\ttc-subway-delay-data-2022.xlsx', 'data/raw\\delay\\ttc-subway-delay-data-2023.xlsx', 'data/raw\\delay\\ttc-subway-delay-data-2024.xlsx', 'data/raw\\delay\\ttc-subway-delay-jan-2014-april-2017.xlsx', 'data/raw\\delay\\ttc-subway-delay-may-december-2017.xlsx', 'data/raw\\ridership\\1985-2019 Analysis of ridership.xlsx', 'data/raw\\ridership\\ttc-subway-station-usage-2012-2013.xlsx', 'data/raw\\ridership\\ttc-subway-station-usage-2014.xlsx', 'data/raw\\ridership\\ttc-subway-station-usage-2015.xlsx', 'data/raw\\ridership\\ttc-subway-station-usage-2016.xlsx', 'data/raw\\ridership\\ttc-subway-station-usage-2017.xlsx', 'data/raw\\schedules\\agency.txt', 'data/raw\\schedules\\calendar.txt', 'data/raw\\schedules\\calendar_dates.txt', 'data/raw\\schedules\\routes.txt', 'data/raw\\schedules\\shapes.txt', 'data/raw\\schedules\\stops.txt', 'data/raw\\schedules\\stop_times.txt', 'data/raw\\schedules\\trips.txt']

 total files: 24

In [150]:
# Verifying routes 

import duckdb

con = duckdb.connect("ttc.duckdb")


con.sql("CREATE OR REPLACE TABLE routes AS SELECT * " \
"FROM read_csv_auto('data/raw/schedules/routes.txt')")


con.sql("SELECT COUNT(route_id) FROM routes GROUP BY route_type").df()

   count(route_id)
0               20
1                3
2              210

In [151]:
con.sql("SELECT route_id, route_short_name, route_long_name " \
"  FROM routes " \
"WHERE route_type = 1").df()

   route_id  route_short_name            route_long_name
0         1                 1  Line 1 (Yonge-University)
1         2                 2  Line 2 (Bloor - Danforth)
2         4                 4          Line 4 (Sheppard)

In [152]:
con.sql("CREATE OR REPLACE TABLE stops AS SELECT * " \
"FROM read_csv_auto('data/raw/schedules/stops.txt')")

con.sql("CREATE OR REPLACE TABLE stop_times AS SELECT * " \
"FROM read_csv_auto('data/raw/schedules/stop_times.txt')")

con.sql("CREATE OR REPLACE TABLE trips AS SELECT * " \
"FROM read_csv_auto('data/raw/schedules/trips.txt')")

In [153]:
# filter in only stop time data related to subway lines

con.sql("""
    CREATE OR REPLACE TABLE subway_stop_times AS
    SELECT stop_times.* FROM trips
    JOIN stop_times 
        ON trips.trip_id = stop_times.trip_id
    WHERE trips.route_id IN [1,2,4]
""")

con.sql("""
    SELECT * FROM subway_stop_times LIMIT 5
""").df()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled
0,50659966,5:45:18,5:45:18,14945,1,None,0,0,NaN
1,50659966,5:47:44,5:47:44,15664,2,None,0,0,1.4442
2,50659966,5:50:22,5:50:22,15659,3,None,0,0,3.3901
3,50659966,5:52:34,5:52:34,15666,4,None,0,0,4.7396
4,50659966,5:54:26,5:54:26,15656,5,None,0,0,5.5524

In [154]:
con.sql("""
    SELECT * FROM stops LIMIT 5
""").df()

,stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station,stop_timezone,wheelchair_boarding
0,662,662,Danforth Rd at Kennedy Rd,None,43.714379,-79.260939,None,None,None,None,None,1
1,929,929,Davenport Rd at Bedford Rd,None,43.674448,-79.399659,None,None,None,None,None,1
2,940,940,Davenport Rd at Dupont St,None,43.675511,-79.401938,None,None,None,None,None,2
3,1871,1871,Davisville Ave at Cleveland St,None,43.702088,-79.378112,None,None,None,None,None,1
4,11700,11700,Disco Rd at Attwell Dr,None,43.701362,-79.594843,None,None,None,None,None,1

In [159]:
## fixing name duplicate i.e Bloor-Yonge

pd.set_option('display.max_rows', 70)

mapping = pd.DataFrame([
    ("Bloor Station", "Bloor-Yonge Station"),
    ("Yonge Station", "Bloor-Yonge Station")
], columns = ["raw_name", "canonical_name"])

con.sql("""
        CREATE OR REPLACE TABLE station_trips AS
        SELECT COALESCE(mapping.canonical_name, SPLIT_PART(stop_name, ' -', 1)) AS stations
        , COUNT(*) AS scheduled_trips
        FROM stops
        JOIN subway_stop_times
            ON subway_stop_times.stop_id = stops.stop_id
        LEFT JOIN mapping ON SPLIT_PART(stop_name, ' -', 1) = mapping.raw_name
        GROUP BY 1
        ORDER BY stations ASC
""")

con.sql("""SELECT * FROM station_trips""").df()

                               stations  scheduled_trips
0                      Bathurst Station             2137
1                           Bay Station             2136
2                       Bayview Station             1755
3                     Bessarion Station             1758
4                   Bloor-Yonge Station             4332
5                     Broadview Station             2133
6                  Castle Frank Station             2133
7                     Cedarvale Station             2181
8                       Chester Station             2133
9                      Christie Station             2139
10                      College Station             2195
11                      Coxwell Station             2158
12                   Davisville Station             2190
13                    Don Mills Station             1761
14                     Donlands Station             2133
15               Downsview Park Station             2154
16                     Dufferin Station             2139
17                  Dundas West Station             2139
18                       Dupont Station             2184
19                     Eglinton Station             2223
20                        Finch Station             2224
21                   Finch West Station             2154
22                    Glencairn Station             2181
23                    Greenwood Station             2158
24                    High Park Station             2155
25                  Highway 407 Station             2154
26                    Islington Station             2155
27                         Jane Station             2155
28                        Keele Station             2155
29                      Kennedy Station             2158
30                         King Station             2195
31                      Kipling Station             2155
32                    Lansdowne Station             2139
33                     Lawrence Station             2223
34                Lawrence West Station             2181
35                       Leslie Station             1761
36                  Main Street Station             2158
37                       Museum Station             2189
38            North York Centre Station             2224
39                     Old Mill Station             2155
40                      Osgoode Station             2191
41                    Ossington Station             2139
42                         Pape Station             2133
43              Pioneer Village Station             2154
44                        Queen Station             2195
45                 Queen's Park Station             2189
46                     Rosedale Station             2196
47                   Royal York Station             2155
48                    Runnymede Station             2155
49                Sheppard West Station             2154
50               Sheppard-Yonge Station             3976
51                   Sherbourne Station             2133
52                      Spadina Station             4321
53                    St Andrew Station             2191
54                     St Clair Station             2196
55                St Clair West Station             2184
56                    St George Station             4326
57                   St Patrick Station             2191
58                   Summerhill Station             2196
59                          TMU Station             2195
60                        Union Station             2195
61  Vaughan Metropolitan Centre Station             2154
62                Victoria Park Station             2158
63                       Warden Station             2158
64                    Wellesley Station             2195
65                       Wilson Station             2181
66                     Woodbine Station             2158
67                   York Mills Station             2224
68                      York University             2154
69                     Yorkdale Station             2181

In [156]:
## Verifying delay datas

paths = glob.glob("data/raw/delay/**")

for f in paths:
    if os.path.splitext(f)[1].lower() == '.xlsx':
        df = pd.read_excel(f, nrows=0)
    else:
        df = pd.read_csv(f, nrows=0)
    print(f, df.columns.tolist())

path = "data/raw/delay/ttc-subway-delay-jan-2014-april-2017.xlsx"
sheets = pd.read_excel(path, sheet_name=None)
print(sheets.keys())

print(sheets['Incidents']['Date'].min())
print(sheets['Incidents']['Date'].max())

data/raw/delay\TTC Subway Delay Data since 2025.csv ['_id', 'Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2018.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2019.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2020.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2021.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2022.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2023.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2024.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-jan-2014-april-2017.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-may-december-2017.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
dict_keys(['Incidents'])
2014-01-01 00:00:00
2017-04-30 00:00:00

In [157]:
paths = glob.glob("data/raw/delay/**")

dfs = []

for f in paths:
    if os.path.splitext(f)[1].lower() == '.xlsx':
        df = pd.read_excel(f)
    else:
        df = pd.read_csv(f)
    dfs.append(df)

all_delays = pd.concat(dfs, ignore_index=True)

## all_delays.shape

(all_delays.dtypes.to_string())

## print(all_delays['Date'].max())
## print(all_delays['Date'].min())

'_id          float64\nDate          object\nTime             str\nDay              str\nStation          str\nCode             str\nMin Delay      int64\nMin Gap        int64\nBound            str\nLine             str\nVehicle        int64'

In [ ]:
pd.set_option('display.max_rows', 100)

con.sql("""
CREATE OR REPLACE TABLE raw_delays AS
SELECT * FROM all_delays 
""")

con.sql("""
WITH ranked AS (
    SELECT
        Station, 
        COUNT(Station) AS count,
        count / SUM(COUNT(*)) OVER () AS ratio,
        SUM(COUNT(*)) OVER (ORDER BY COUNT(*) DESC) as r_total,
        r_total / SUM(COUNT(*)) OVER () AS r_ratio,
        ROW_NUMBER() OVER (ORDER BY COUNT(*) DESC) AS r_num
    FROM raw_delays
    GROUP BY Station
    ORDER BY Count DESC
)
SELECT * FROM ranked WHERE r_num IN (70,150)
""").df()

                  Station  count     ratio   r_total   r_ratio  r_num
0       RUNNYMEDE STATION   1046  0.005596  168234.0  0.900051     70
1  VMC STATION PLATFORM 2     19  0.000102  183545.0  0.981965    150

In [ ]:
con.sql("""
SELECT * FROM all_delays
""").df()

,_id,Date,Time,Day,Station,Code,Min Delay,Min Gap,Bound,Line,Vehicle
0,1.0,2025-01-01,02:10,Wednesday,BATHURST STATION,MUSAN,5,9,E,BD,5227
1,2.0,2025-01-01,02:30,Wednesday,DUNDAS STATION,MUIRS,0,0,NaN,YU,0
2,3.0,2025-01-01,02:32,Wednesday,BROADVIEW STATION,PUMST,0,0,E,BD,0
3,4.0,2025-01-01,02:58,Wednesday,KEELE STATION,EUSC,0,0,W,BD,5293
4,5.0,2025-01-01,02:58,Wednesday,COXWELL STATION,SUAE,0,0,NaN,BD,0
...,...,...,...,...,...,...,...,...,...,...,...
186911,NaN,2017-05-31 00:00:00,23:14,Wednesday,WILSON STATION (EXITIN,TUMVS,0,0,N,YU,5736
186912,NaN,2017-05-31 00:00:00,23:23,Wednesday,ST CLAIR WEST,SUDP,0,0,N,YU,5821
186913,NaN,2017-05-31 00:00:00,23:30,Wednesday,YONGE UNIVERSITY SUBWA,MUGD,0,0,NaN,YU,0
186914,NaN,2017-05-31 00:00:00,23:41,Wednesday,KENNEDY SRT STATION,MRTO,4,11,S,SRT,3021
186915,NaN,2017-05-31 00:00:00,23:59,Wednesday,GLENCAIRN STATION,MUSC,0,0,S,YU,5726

In [ ]:
pd.set_option('display.max_rows', None)

con.sql("""
CREATE OR REPLACE TABLE clean_delays AS 
    WITH s1 AS (
        SELECT * REPLACE (REGEXP_REPLACE(Station, ' STATION$', '') AS Station) FROM raw_delays),
    s2 AS (
        SELECT * REPLACE (REGEXP_REPLACE(Station, ' (BD|YU|YUS|SRT)$', '') AS Station) FROM s1)
SELECT * FROM s2
""")

result = con.sql("""
SELECT DISTINCT Station FROM clean_delays WHERE Station LIKE '%STATION%'
""").df()

print(result.to_string())

           Date   Time        Day                 Station   Code  Min Delay  Min Gap Bound Line  Vehicle
0    2017-05-01  00:18     Monday  KIPLING STATION (ENTER   TUSC          0        0     W   BD     5251
1    2017-05-01  00:58     Monday       ISLINGTON STATION   MUSC          0        0     W   BD     5182
2    2017-05-01  01:07     Monday  UNION STATION (DOWNSVI  MUPAA          3        7     N   YU     5811
3    2017-05-01  01:18     Monday         MCCOWAN STATION   MRTO          4        9     S  SRT     3006
4    2017-05-01  01:42     Monday    CASTLE FRANK STATION    MUO          7       11     W   BD     5296
5    2017-05-01  05:56     Monday            JANE STATION   EUBK          5        0     W   BD     5056
6    2017-05-01  06:18     Monday        OLD MILL STATION   MUSC          0        0     E   BD     5277
7    2017-05-01  06:26     Monday          DUNDAS STATION    MUI         16       21     S   YU     6121
8    2017-05-01  06:31     Monday   EGLINTON WEST STATION   EUDO          3        5     S   YU     6081
9    2017-05-01  06:52     Monday     DUNDAS WEST STATION   EUDO          7        9     W   BD     5119
10   2017-05-01  07:03     Monday          LESLIE STATION   TUSC          0        0     W  SHP     6181
11   2017-05-01  07:10     Monday      KENNEDY BD STATION   EUNT          0        0     W   BD     5056
12   2017-05-01  07:12     Monday       ISLINGTON STATION   MUSC          3        5     E   BD     5283
13   2017-05-01  07:15     Monday        WOODBINE STATION   MUDD          0        0     E   BD     5115
14   2017-05-01  07:29     Monday         CHESTER STATION   MUSC          0        0     W   BD     5294
15   2017-05-01  07:40     Monday             BAY STATION   MUSC          0        0     W   BD     5294
16   2017-05-01  07:45     Monday        BATHURST STATION  MUPAA          4        6     W   BD     5127
17   2017-05-01  07:56     Monday       RUNNYMEDE STATION   MUSC          0        0     W   BD     5294
18   2017-05-01  08:05     Monday       ISLINGTON STATION   MUSC          0        0     W   BD     5294
19   2017-05-01  08:21     Monday       ELLESMERE STATION   TRTC          4        9     S  SRT     3010
20   2017-05-01  08:43     Monday      SHERBOURNE STATION   EUVA          7        9     E   BD     5085
21   2017-05-01  08:50     Monday      YORK MILLS STATION  TUMVS          0        0     N   YU     5511
22   2017-05-01  09:23     Monday       ISLINGTON STATION   MUSC          0        0     E   BD     5341
23   2017-05-01  09:50     Monday        BATHURST STATION   TUSC          0        0     E   BD     5177
24   2017-05-01  09:56     Monday         KIPLING STATION   MUSC          0        0     E   BD     5102
25   2017-05-01  09:57     Monday         KIPLING STATION   MUSC          0        0     E   BD     5159
26   2017-05-01  09:57     Monday          DUNDAS STATION    MUI          5        7     S   YU     6131
27   2017-05-01  10:05     Monday             BAY STATION  MUPR1         40       43     E   BD     5003
28   2017-05-01  10:23     Monday       ISLINGTON STATION   PUSO          0        0     E   BD     5078
29   2017-05-01  10:28     Monday        EGLINTON STATION   MUIE          0        0   NaN   YU        0
30   2017-05-01  11:10     Monday       GREENWOOD STATION   TUSC          0        0     W   BD     5048
31   2017-05-01  11:15     Monday         COXWELL STATION   MUSC          0        0     W   BD     5048
32   2017-05-01  11:21     Monday    ST GEORGE BD STATION   MUIR          8       11     W   BD     5028
33   2017-05-01  11:52     Monday     KENNEDY SRT STATION    MRO          5       10     S  SRT     3002
34   2017-05-01  11:58     Monday            PAPE STATION  PUMEL          0        0   NaN   BD        0
35   2017-05-01  12:11     Monday      ROYAL YORK STATION   MUIS          0        0     E   BD        0
36   2017-05-01  12:14     Monday       ISLINGTON STATION   MUSC          0        0     E   BD     5283
37   2017-05-01  12:15     Monday  JANE STATION (APPROACH  MUPLB          4        7     W   BD     5112
38   2017-05-01  12:17     Monday          LESLIE STATION   TUSC          0        0     W  SHP     6471
39   2017-05-01  12:26     Monday        BATHURST STATION   MUIS          0        0   NaN   BD        0
40   2017-05-01  12:42     Monday     KENNEDY SRT STATION   MRTO          0        0     S  SRT     3019
41   2017-05-01  12:57     Monday        CHRISTIE STATION  MUPAA          3        6     W   BD     5164
42   2017-05-01  13:41     Monday     KENNEDY SRT STATION   MRTO          0        0     S  SRT     3006
43   2017-05-01  13:46     Monday       ELLESMERE STATION   MRTO          0        0     S  SRT     3000
44   2017-05-01  14:29     Monday           BLOOR STATION  MUPAA          0        0     N   YU     5911
45   2017-05-01  14:49     Monday        CHRISTIE STATION   MUSC          0        0     W   BD     5083
46   2017-05-01  14:49     Monday          WILSON STATION   EUPI          3        6     N   YU     5686
47   2017-05-01  15:34     Monday      ST PATRICK STATION   TUSC          0        0   NaN   YU     5686
48   2017-05-01  15:41     Monday       DOWNSVIEW STATION   EUBK          4        7     S   YU     5691
49   2017-05-01  15:52     Monday       GLENCAIRN STATION  MUNCA          0        0   NaN   YU        0
50   2017-05-01  16:11     Monday        OLD MILL STATION   MUSC          0        0     E   BD     5283
51   2017-05-01  16:14     Monday   VICTORIA PARK STATION   MUSC          0        0     W   BD     5076
52   2017-05-01  16:38     Monday      KENNEDY BD STATION   MUSC          0        0     W   BD     5072
53   2017-05-01  16:49     Monday      ST PATRICK STATION  PUMST          0        0   NaN   YU        0
54   2017-05-01  16:53     Monday   ST CLAIR WEST STATION   SUDP          3        5     S   YU     5836
55   2017-05-01  17:37     Monday    ST GEORGE BD STATION   MUDD          4        6     W   BD     5130
56   2017-05-01  17:42     Monday  WOODBINE STATION (LEAV   MUSC          0        0     W   BD     5243
57   2017-05-01  17:50     Monday     DUNDAS WEST STATION  SUCOL          0        0     W   BD     5264
58   2017-05-01  17:55     Monday         COXWELL STATION   EUBK          0        0     E   BD     5135
59   2017-05-01  17:56     Monday  KENNEDY BD STATION (AP   TUSC          0        0     E   BD     5272
60   2017-05-01  17:57     Monday        OLD MILL STATION   MUSC          0        0     E   BD     5283
61   2017-05-01  18:00     Monday  NORTH YORK CTR STATION  MUPAA          0        0     N   YU     5751
62   2017-05-01  18:21     Monday        SHEPPARD STATION  MUIRS          3        5     S   YU     5641
63   2017-05-01  18:46     Monday      KENNEDY BD STATION   MUSC          0        0     W   BD     5191
64   2017-05-01  18:53     Monday     KENNEDY SRT STATION   SRDP          9       16     N  SRT     3023
65   2017-05-01  20:10     Monday     KENNEDY SRT STATION   MRTO          0        0     S  SRT     3019
66   2017-05-01  20:18     Monday     KENNEDY SRT STATION   MRTO          0        0     S  SRT     3023
67   2017-05-01  20:26     Monday   LAWRENCE WEST STATION  PUMEL          0        0   NaN   YU        0
68   2017-05-01  20:32     Monday         MCCOWAN STATION   MRTO          0        0     S  SRT     3006
69   2017-05-01  20:44     Monday       GREENWOOD STATION   MUSC          0        0     W   BD     5336
70   2017-05-01  20:55     Monday       ISLINGTON STATION  PUMST          0        0   NaN   BD        0
71   2017-05-01  22:00     Monday  YONGE-UNIVERSITY AND B    MUO          0        0   NaN   BD        0
72   2017-05-01  22:17     Monday  OLD MILL STATION (EXIT  PUSTC          7       11     E   BD     5099
73   2017-05-01  22:27     Monday        OLD MILL STATION   SUDP          3        7     E   BD     5137
74   2017-05-01  22:39     Monday   EGLINTON WEST STATION   MUSC          0        0     N   YU     5761
75   2017-05-01  22:51     Monday      ST PATRICK STATION   MUIS          0        0   NaN   YU        0
76   2017-05-01  22:58     Monday           KEELE STATION   MUSC          0        0     E   BD     5298
77   2017-05-01  23:07     Monday        YONGE BD STATION  MUPAA          5        9     W   BD     5225
78   2017-05-01  23:07     Monday     KENNEDY SRT STATION   MRTO          9       14     S  SRT     3006
79   2017-05-01  23:25     Monday   YONGE-UNIVERSITY LINE   MUGD          0        0   NaN   YU        0
80   2017-05-01  23:30     Monday   BLOOR DANFORTH SUBWAY   MUGD          0        0   NaN   BD        0
81   2017-05-01  23:32     Monday        LAWRENCE STATION   MUIR          3        7     S   YU     6131
82   2017-05-01  23:34     Monday  OLD MILL STATION (APPR   TUSC          0        0     E   BD     5307
83   2017-05-01  23:57     Monday        SHEPPARD STATION  PUMEL          0        0   NaN  SHP        0
84   2017-05-02  00:33    Tuesday      YORK MILLS STATION   MUIS          0        0     S   YU        0
85   2017-05-02  00:45    Tuesday        DUFFERIN STATION   MUSC          0        0     E   BD     5307
86   2017-05-02  01:05    Tuesday        OLD MILL STATION    SUO          0        0     E   BD     5264
87   2017-05-02  01:11    Tuesday         BAYVIEW STATION   MUSC          0        0     E  SHP     6176
88   2017-05-02  01:21    Tuesday        BATHURST STATION    MUI         12       16     E   BD     5264
89   2017-05-02  01:35    Tuesday         COLLEGE STATION   MUIR          0        0     S   YU     5421
90   2017-05-02  05:12    Tuesday       ST GEORGE STATION   PUMO          0        0     N   YU        0
91   2017-05-02  05:41    Tuesday         MCCOWAN STATION   ERDO          9       14     N  SRT     3002
92   2017-05-02  06:19    Tuesday      KENNEDY BD STATION   MUSC          0        0     E   BD     5182
93   2017-05-02  06:25    Tuesday   LAWRENCE EAST STATION   MRTO          0        0     N  SRT     3015
94   2017-05-02  06:30    Tuesday  DUPONT STATION (APPROA  TUMVS          4        6     S   YU     5381
95   2017-05-02  06:42    Tuesday       ELLESMERE STATION   MRTO          8       13     S  SRT     3002
96   2017-05-02  07:14    Tuesday       GREENWOOD STATION   MUSC          0        0     E   BD     5099
97   2017-05-02  07:17    Tuesday       GREENWOOD STATION   EUNT          0        0     W   BD     5061
98   2017-05-02  07:17    Tuesday           FINCH STATION   MUSC          0        0     S   YU     5386
99   2017-05-02  07:20    Tuesday      SPADINA BD STATION   EUDO          5        7     E   BD     5256
100  2017-05-02  07:24    Tuesday         KIPLING STATION   MUSC          0        0     E   BD     5294
101  2017-05-02  07:29    Tuesday  YORK MILLS STATION (AP   TUSC          0        0     S   YU     5536
102  2017-05-02  07:30    Tuesday      SHERBOURNE STATION   EUCD          7        9     E   BD     5256
103  2017-05-02  07:51    Tuesday         MCCOWAN STATION   PRSW          3        8     N  SRT        0
104  2017-05-02  09:21    Tuesday   EGLINTON WEST STATION   TUSC          0        0     N   YU     5126
105  2017-05-02  09:24    Tuesday   BLOOR DANFORTH SUBWAY  PUCSS          0        0   NaN   BD        0
106  2017-05-02  09:26    Tuesday    SHEPPARD SUBWAY LINE  PUCSS          0        0   NaN  SHP        0
107  2017-05-02  10:12    Tuesday             BAY STATION  MUPAA          0        0     E   BD     5329
108  2017-05-02  10:24    Tuesday       BROADVIEW STATION  MUPAA          0        0     E   BD     5329
109  2017-05-02  10:36    Tuesday       WELLESLEY STATION   SUDP          4        6     N   YU     5976
110  2017-05-02  10:51    Tuesday   BLOOR DANFORTH SUBWAY    MUO          0        0   NaN   BD        0
111  2017-05-02  10:56    Tuesday        ST CLAIR STATION   MUSC          0        0     S   YU     2368
112  2017-05-02  11:40    Tuesday        EGLINTON STATION  TUNIP          4        7     S   YU     5421
113  2017-05-02  11:41    Tuesday            PAPE STATION   SUDP         12       15     W   BD     5332
114  2017-05-02  11:46    Tuesday        YONGE BD STATION   MUIS          0        0     W   BD        0
115  2017-05-02  12:00    Tuesday           BLOOR STATION   MUIR          0        0     S   YU     5676
116  2017-05-02  13:45    Tuesday   ST GEORGE YUS STATION   MUSC          0        0     S   YU     5411
117  2017-05-02  13:46    Tuesday           BLOOR STATION   MUIS          0        0     S   YU        0
118  2017-05-02  14:07    Tuesday    DUNDAS STATION E/S 1   MUIS          0        0   NaN   YU        0
119  2017-05-02  14:22    Tuesday         COXWELL STATION  MUPAA          0        0     E   BD     5206
120  2017-05-02  15:31    Tuesday            PAPE STATION   EUAL          3        5     E   BD     5155
121  2017-05-02  15:32    Tuesday           FINCH STATION   TUSC          0        0     N   YU     6066
122  2017-05-02  16:31    Tuesday        WOODBINE STATION   MUSC          0        0     W   BD     5121
123  2017-05-02  16:48    Tuesday   VICTORIA PARK STATION  MUPAA          0        0     E   BD     5078
124  2017-05-02  16:56    Tuesday      SPADINA BD STATION   SUDP          3        5     E   BD     5277
125  2017-05-02  17:06    Tuesday       BROADVIEW STATION    MUD          6        8     E   BD     5230
126  2017-05-02  17:17    Tuesday      KENNEDY BD STATION  MUSAN          3        5     W   BD     5159
127  2017-05-02  17:27    Tuesday      SUMMERHILL STATION   MUIR          0        0     N   YU     6066
128  2017-05-02  17:36    Tuesday  ISLINGTON STATION (APP   MUSC          0        0     E   BD     5096
129  2017-05-02  17:41    Tuesday     MAIN STREET STATION  MUPAA          6        8     W   BD     5085
130  2017-05-02  17:46    Tuesday          MUSEUM STATION   MUSC          0        0     N   YU     5721
131  2017-05-02  17:47    Tuesday           BLOOR STATION  MUPAA          0        0     S   YU     5876
132  2017-05-02  17:48    Tuesday  KENNEDY STATION (PALTF   EUBK          0        0     W   BD     5182
133  2017-05-02  17:50    Tuesday         CHESTER STATION  PUTDN          6        8     E   BD     5269
134  2017-05-02  18:12    Tuesday        BATHURST STATION   MUIS          0        0   NaN   BD        0
135  2017-05-02  18:13    Tuesday        BATHURST STATION    MUD          3        5     E   BD     5296
136  2017-05-02  18:31    Tuesday  HIGH PARK STATION (ENT   MUSC          0        0     E   BD     5099
137  2017-05-02  19:36    Tuesday      YORK MILLS STATION   MUSC          0        0     N   YU     5836
138  2017-05-02  19:56    Tuesday             BAY STATION  PUTIJ          0        0     W   BD     5064
139  2017-05-02  20:16    Tuesday        SHEPPARD STATION  TUMVS          0        0     S   YU     5941
140  2017-05-02  20:51    Tuesday      KENNEDY BD STATION   SUSA          0        0   NaN   BD        0
141  2017-05-02  21:21    Tuesday   ST GEORGE YUS STATION   MUSC          0        0     N   YU     5421
142  2017-05-02  22:02    Tuesday         WILSON CARHOUSE    MUO          0        0   NaN   YU        0
143  2017-05-02  22:06    Tuesday          WILSON STATION   TUSC          0        0     N   YU     5786
144  2017-05-02  23:15    Tuesday   BLOOR DANFORTH SUBWAY   MUGD          0        0   NaN   BD        0
145  2017-05-02  23:27    Tuesday  YONGE UNIVERSITY SUBWA   MUGD          0        0   NaN   YU        0
146  2017-05-03  00:57  Wednesday   LAWRENCE WEST STATION   TUSC          0        0     N   YU     5826
147  2017-05-03  01:11  Wednesday       LANSDOWNE STATION   SUAP         11       15     W   BD     5313
148  2017-05-03  01:45  Wednesday      KENNEDY BD STATION   SUDP          0        0   NaN   BD        0
149  2017-05-03  01:59  Wednesday      KENNEDY BD STATION   MUSC          0        0     W   BD     5244
150  2017-05-03  06:07  Wednesday   LAWRENCE EAST STATION   MRTO          0        0     N  SRT     3009
151  2017-05-03  06:20  Wednesday           UNION STATION  PUSTS          3        8     N   YU     5521
152  2017-05-03  06:28  Wednesday  WILSON STATION (APPROA   MUSC          0        0     S   YU     5451
153  2017-05-03  06:41  Wednesday         MCCOWAN STATION   ERTC         10       15     N  SRT     3009
154  2017-05-03  07:30  Wednesday       GREENWOOD STATION  EUYRD          5        7     E   BD     5256
155  2017-05-03  07:46  Wednesday       HIGH PARK STATION   MUSC          0        0     E   BD     5307
156  2017-05-03  07:49  Wednesday        ST CLAIR STATION  MUPAA          0        0     S   YU     5676
157  2017-05-03  07:55  Wednesday   ST CLAIR WEST STATION  MUPAA          0        0     N   YU     5921
158  2017-05-03  08:17  Wednesday       OSSINGTON STATION   TUSC          0        0     W   BD     5012
159  2017-05-03  08:29  Wednesday      YORK MILLS STATION    MUI          7        9     N   YU     6121
160  2017-05-03  08:30  Wednesday   LAWRENCE WEST STATION   MUSC          0        0     S   YU     5451
161  2017-05-03  08:45  Wednesday          DUPONT STATION   MUIE          0        0   NaN   YU        0
162  2017-05-03  08:56  Wednesday     MAIN STREET STATION   MUSC         11       13     E   BD     5136
163  2017-05-03  09:02  Wednesday    CASTLE FRANK STATION   MUSC          0        0     E   BD     5294
164  2017-05-03  09:16  Wednesday            JANE STATION   EUDO          3        5     E   BD     5102
165  2017-05-03  09:17  Wednesday            PAPE STATION   MUSC          0        0     E   BD     5332
166  2017-05-03  09:40  Wednesday         MIDLAND STATION  TRNCA          0        0   NaN  SRT        0
167  2017-05-03  09:45  Wednesday  YORK MILLS STATION (AP   MUSC          0        0     N   YU     6091
168  2017-05-03  10:04  Wednesday   ST GEORGE YUS STATION   MUIS          0        0   NaN   YU        0
169  2017-05-03  12:32  Wednesday        SHEPPARD STATION   MUIS          0        0   NaN   YU        0
170  2017-05-03  12:58  Wednesday        ROSEDALE STATION   SUDP          0        0     N   YU     5661
171  2017-05-03  13:51  Wednesday         KIPLING STATION   MUSC          0        0     E   BD     5068
172  2017-05-03  14:29  Wednesday     KENNEDY SRT STATION   MRTO          0        0     S  SRT     3012
173  2017-05-03  14:57  Wednesday  ROYAL YORK STATION (AP   TUSC          0        0     E   BD     5284
174  2017-05-03  15:14  Wednesday  ISLINGTON STATION (APP   MUSC          0        0     W   BD     5107
175  2017-05-03  15:52  Wednesday   ST GEORGE YUS STATION   TUSC          0        0     S   YU     5906
176  2017-05-03  16:02  Wednesday                 KENNEDY   MRTO          0        0     S  SRT     3006
177  2017-05-03  16:06  Wednesday    ST GEORGE BD STATION   MUSC          0        0     E   BD     5246
178  2017-05-03  16:26  Wednesday   ST GEORGE YUS STATION  MUIRS          0        0   NaN   YU        0
179  2017-05-03  16:34  Wednesday         KIPLING STATION   MUSC          0        0     E   BD     5259
180  2017-05-03  16:49  Wednesday       WELLESLEY STATION  MUPAA          3        5     N   YU     5591
181  2017-05-03  17:01  Wednesday         CHESTER STATION   TUSC          0        0     E   BD     5192
182  2017-05-03  17:22  Wednesday           FINCH STATION  PUSRA          3        5     S   YU     5596
183  2017-05-03  17:24  Wednesday        ROSEDALE STATION  MUPAA          0        0     N   YU     5931
184  2017-05-03  17:36  Wednesday  DUPONT STATION (APPROA   TUSC          0        0     S   YU     5836
185  2017-05-03  17:41  Wednesday     KENNEDY SRT STATION   MRTO          0        0     S  SRT     3006
186  2017-05-03  18:03  Wednesday          WARDEN STATION  MUNCA          0        0   NaN   BD        0
187  2017-05-03  18:09  Wednesday        YORKDALE STATION  MUNCA          0        0   NaN   YU        0
188  2017-05-03  18:11  Wednesday     KENNEDY SRT STATION   MRTO          0        0     N  SRT     3001