In [47]:
# Verifying data path

import os
import glob
import pandas as pd

paths = glob.glob("data/raw/**/*", recursive=True)

files = []
for item in paths:
    if os.path.isfile(item):
        files.append(item)

length = len(files)

print(files)
print(f"\n total files: {length}")

['data/raw\\delay\\TTC Subway Delay Data since 2025.csv', 'data/raw\\delay\\ttc-subway-delay-data-2018.xlsx', 'data/raw\\delay\\ttc-subway-delay-data-2019.xlsx', 'data/raw\\delay\\ttc-subway-delay-data-2020.xlsx', 'data/raw\\delay\\ttc-subway-delay-data-2021.xlsx', 'data/raw\\delay\\ttc-subway-delay-data-2022.xlsx', 'data/raw\\delay\\ttc-subway-delay-data-2023.xlsx', 'data/raw\\delay\\ttc-subway-delay-data-2024.xlsx', 'data/raw\\delay\\ttc-subway-delay-jan-2014-april-2017.xlsx', 'data/raw\\delay\\ttc-subway-delay-may-december-2017.xlsx', 'data/raw\\ridership\\1985-2019 Analysis of ridership.xlsx', 'data/raw\\ridership\\ttc-subway-station-usage-2012-2013.xlsx', 'data/raw\\ridership\\ttc-subway-station-usage-2014.xlsx', 'data/raw\\ridership\\ttc-subway-station-usage-2015.xlsx', 'data/raw\\ridership\\ttc-subway-station-usage-2016.xlsx', 'data/raw\\ridership\\ttc-subway-station-usage-2017.xlsx', 'data/raw\\schedules\\agency.txt', 'data/raw\\schedules\\calendar.txt', 'data/raw\\schedules\\calendar_dates.txt', 'data/raw\\schedules\\routes.txt', 'data/raw\\schedules\\shapes.txt', 'data/raw\\schedules\\stops.txt', 'data/raw\\schedules\\stop_times.txt', 'data/raw\\schedules\\trips.txt']

 total files: 24

In [48]:
# Verifying routes 

import duckdb

con = duckdb.connect("ttc.duckdb")


con.sql("CREATE OR REPLACE TABLE routes AS SELECT * " \
"FROM read_csv_auto('data/raw/schedules/routes.txt')")


con.sql("SELECT COUNT(route_id) FROM routes GROUP BY route_type").df()

   count(route_id)
0               20
1                3
2              210

In [49]:
con.sql("SELECT route_id, route_short_name, route_long_name " \
"  FROM routes " \
"WHERE route_type = 1").df()

   route_id  route_short_name            route_long_name
0         1                 1  Line 1 (Yonge-University)
1         2                 2  Line 2 (Bloor - Danforth)
2         4                 4          Line 4 (Sheppard)

In [50]:
con.sql("CREATE OR REPLACE TABLE stops AS SELECT * " \
"FROM read_csv_auto('data/raw/schedules/stops.txt')")

con.sql("CREATE OR REPLACE TABLE stop_times AS SELECT * " \
"FROM read_csv_auto('data/raw/schedules/stop_times.txt')")

con.sql("CREATE OR REPLACE TABLE trips AS SELECT * " \
"FROM read_csv_auto('data/raw/schedules/trips.txt')")

In [51]:
# filter in only stop time data related to subway lines

con.sql("""
    CREATE OR REPLACE TABLE subway_stop_times AS
    SELECT stop_times.* FROM trips
    JOIN stop_times 
        ON trips.trip_id = stop_times.trip_id
    WHERE trips.route_id IN [1,2,4]
""")

con.sql("""
    SELECT * FROM subway_stop_times LIMIT 5
""").df()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled
0,50659966,5:45:18,5:45:18,14945,1,None,0,0,NaN
1,50659966,5:47:44,5:47:44,15664,2,None,0,0,1.4442
2,50659966,5:50:22,5:50:22,15659,3,None,0,0,3.3901
3,50659966,5:52:34,5:52:34,15666,4,None,0,0,4.7396
4,50659966,5:54:26,5:54:26,15656,5,None,0,0,5.5524

In [52]:
con.sql("""
    SELECT * FROM stops LIMIT 5
""").df()

,stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station,stop_timezone,wheelchair_boarding
0,662,662,Danforth Rd at Kennedy Rd,None,43.714379,-79.260939,None,None,None,None,None,1
1,929,929,Davenport Rd at Bedford Rd,None,43.674448,-79.399659,None,None,None,None,None,1
2,940,940,Davenport Rd at Dupont St,None,43.675511,-79.401938,None,None,None,None,None,2
3,1871,1871,Davisville Ave at Cleveland St,None,43.702088,-79.378112,None,None,None,None,None,1
4,11700,11700,Disco Rd at Attwell Dr,None,43.701362,-79.594843,None,None,None,None,None,1

In [53]:

pd.set_option('display.max_rows', 100)

mapping = pd.DataFrame([
    ("Bloor Station", "Bloor-Yonge Station"),
    ("Yonge Station", "Bloor-Yonge Station")
], columns = ["raw_name", "canonical_name"])

con.sql("""
        CREATE OR REPLACE TABLE station_trips AS
        SELECT COALESCE(mapping.canonical_name, SPLIT_PART(stop_name, ' -', 1)) AS stations
        , COUNT(*) AS scheduled_trips
        FROM stops
        JOIN subway_stop_times
            ON subway_stop_times.stop_id = stops.stop_id
        LEFT JOIN mapping ON SPLIT_PART(stop_name, ' -', 1) = mapping.raw_name
        GROUP BY 1
        ORDER BY stations ASC
""")

con.sql("""SELECT * FROM station_trips""").df()

                               stations  scheduled_trips
0                      Bathurst Station             2137
1                           Bay Station             2136
2                       Bayview Station             1755
3                     Bessarion Station             1758
4                   Bloor-Yonge Station             4332
5                     Broadview Station             2133
6                  Castle Frank Station             2133
7                     Cedarvale Station             2181
8                       Chester Station             2133
9                      Christie Station             2139
10                      College Station             2195
11                      Coxwell Station             2158
12                   Davisville Station             2190
13                    Don Mills Station             1761
14                     Donlands Station             2133
15               Downsview Park Station             2154
16                     Dufferin Station             2139
17                  Dundas West Station             2139
18                       Dupont Station             2184
19                     Eglinton Station             2223
20                        Finch Station             2224
21                   Finch West Station             2154
22                    Glencairn Station             2181
23                    Greenwood Station             2158
24                    High Park Station             2155
25                  Highway 407 Station             2154
26                    Islington Station             2155
27                         Jane Station             2155
28                        Keele Station             2155
29                      Kennedy Station             2158
30                         King Station             2195
31                      Kipling Station             2155
32                    Lansdowne Station             2139
33                     Lawrence Station             2223
34                Lawrence West Station             2181
35                       Leslie Station             1761
36                  Main Street Station             2158
37                       Museum Station             2189
38            North York Centre Station             2224
39                     Old Mill Station             2155
40                      Osgoode Station             2191
41                    Ossington Station             2139
42                         Pape Station             2133
43              Pioneer Village Station             2154
44                        Queen Station             2195
45                 Queen's Park Station             2189
46                     Rosedale Station             2196
47                   Royal York Station             2155
48                    Runnymede Station             2155
49                Sheppard West Station             2154
50               Sheppard-Yonge Station             3976
51                   Sherbourne Station             2133
52                      Spadina Station             4321
53                    St Andrew Station             2191
54                     St Clair Station             2196
55                St Clair West Station             2184
56                    St George Station             4326
57                   St Patrick Station             2191
58                   Summerhill Station             2196
59                          TMU Station             2195
60                        Union Station             2195
61  Vaughan Metropolitan Centre Station             2154
62                Victoria Park Station             2158
63                       Warden Station             2158
64                    Wellesley Station             2195
65                       Wilson Station             2181
66                     Woodbine Station             2158
67                   York Mills Station             2224
68                      York University             2154
69                     Yorkdale Station             2181

In [65]:
paths = glob.glob("data/raw/delay/**")

for f in paths:
    if os.path.splitext(f)[1].lower() == '.xlsx':
        df = pd.read_excel(f, nrows=0)
    else:
        df = pd.read_csv(f, nrows=0)
    print(f, df.columns.tolist())

path = "data/raw/delay/ttc-subway-delay-jan-2014-april-2017.xlsx"
sheets = pd.read_excel(path, sheet_name=None)
print(sheets.keys())

print(sheets['Incidents']['Date'].min())
print(sheets['Incidents']['Date'].max())

data/raw/delay\TTC Subway Delay Data since 2025.csv ['_id', 'Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2018.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2019.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2020.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2021.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2022.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2023.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2024.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-jan-2014-april-2017.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-may-december-2017.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
dict_keys(['Incidents'])
2014-01-01 00:00:00
2017-04-30 00:00:00